<a href="https://colab.research.google.com/github/borjabmadurga2-creator/Data-Analytics---Borja/blob/main/Sprint10_Borja_Belmonte.ipynb/sprint10_Borja_Belmonte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En este sprint, aplicaremos lo aprendido sobre APIs REST, métodos HTTP y códigos de estado, usando APIs públicas para consultar datos, filtrarlos y finalmente, guardalos en un DataFrame de pandas.

Recursos:

Nivel 1:
{JSON} Placeholder

Nivel 2:
Try Public APIs for free

Nivel 3:
Open Data BCN

**Nivel 1**

Usando la librería "requests", haremos lo siguiente:

Exploración básica con una API de laboratorio.

Consulta la API púlica JSONPlaceholder usando el método GET para obtener:

- Lista de publicaciones (/posts)
- Lista de usuarios (/users)
- Lista de tareas (/todos)

In [35]:
#importación librería requests (google colab ya la tiene instalada)
import requests
import json
import pandas as pd

In [36]:

#agrego la url a una variable para obtener la lista de publicaciones
url_posts = "https://jsonplaceholder.typicode.com/posts"

lista_publicaciones = requests.get(url_posts)
lista_publicaciones.json()

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'},
 {'userId': 1,
  'id': 4,
  'title': 'eum et est occaecati',
  'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'},
 {'userId': 1,
  'id': 5,
  'title': 'nesciunt quas odio',
  'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'},
 {'userId': 1,
  'id': 6,
  'title': 'dolorem eum magni eos aperiam quia',
  'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'},
 {'userId': 1,
  'id': 7,
  'title': 'magnam facilis autem',
  'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'},
 {'userId': 1,
  'id': 8,
  'title': 'dolorem dolore est ipsam',
  'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'},
 {'userId': 1,
  'id': 9,
  'title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'},
 {'userId': 1,
  'id': 10,
  'title': 'optio molestias id quia eum',
  'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'},
 {'userId': 2,
  'id': 11,
  'title': 'et ea vero quia laudantium autem',
  'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'},
 {'userId': 2,
  'id': 12,
  'title': 'in quibusdam tempore odit est dolorem',
  'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'},
 {'userId': 2,
  'id': 13,
  'title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'},
 {'userId': 2,
  'id': 14,
  'title': 'voluptatem eligendi optio',
  'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'},
 {'userId': 2,
  'id': 15,
  'title': 'eveniet quod temporibus',
  'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'},
 {'userId': 2,
  'id': 16,
  'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio',
  'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'},
 {'userId': 2,
  'id': 17,
  'title': 'fugit voluptas sed molestias voluptatem provident',
  'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'},
 {'userId': 2,
  'id': 18,
  'title': 'voluptate et itaque vero tempora molestiae',
  'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'},
 {'userId': 2,
  'id': 19,
  'title': 'adipisci placeat illum aut reiciendis qui',
  'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'},
 {'userId': 2,
  'id': 20,
  'title': 'doloribus ad provident suscipit at',
  'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'},
 {'userId': 3,
  'id': 21,
  'title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'},
 {'userId': 3,
  'id': 22,
  'title': 'dolor sint quo a velit explicabo quia nam',
  'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'},
 {'userId': 3,
  'id': 23,
  'title': 'maxime id vitae nihil numquam',
  'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'},
 {'userId': 3,
  'id': 24,
  'title': 'autem hic labore sunt dolores incidunt',
  'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'},
 {'userId': 3,
  'id': 25,
  'title': 'rem alias distinctio quo quis',
  'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'},
 {'userId': 3,
  'id': 26,
  'title': 'est et quae odit qui non',
  'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'},
 {'userId': 3,
  'id': 27,
  'title': 'quasi id et eos tenetur aut quo autem',
  'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'},
 {'userId': 3,
  'id': 28,
  'title': 'delectus ullam et corporis nulla voluptas sequi',
  'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'},
 {'userId': 3,
  'id': 29,
  'title': 'iusto eius quod necessitatibus culpa ea',
  'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'},
 {'userId': 3,
  'id': 30,
  'title': 'a quo magni similique perferendis',
  'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'},
 {'userId': 4,
  'id': 31,
  'title': 'ullam ut quidem id aut vel consequuntur',
  'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'},
 {'userId': 4,
  'id': 32,
  'title': 'doloremque illum aliquid sunt',
  'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'},
 {'userId': 4,
  'id': 33,
  'title': 'qui explicabo molestiae dolorem',
  'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'},
 {'userId': 4,
  'id': 34,
  'title': 'magnam ut rerum iure',
  'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'},
 {'userId': 4,
  'id': 35,
  'title': 'id nihil consequatur molestias animi provident',
  'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'},
 {'userId': 4,
  'id': 36,
  'title': 'fuga nam accusamus voluptas reiciendis itaque',
  'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'},
 {'userId': 4,
  'id': 37,
  'title': 'provident vel ut sit ratione est',
  'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'},
 {'userId': 4,
  'id': 38,
  'title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'},
 {'userId': 4,
  'id': 39,
  'title': 'eos dolorem iste accusantium est eaque quam',
  'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'},
 {'userId': 4,
  'id': 40,
  'title': 'enim quo cumque',
  'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'},
 {'userId': 5,
  'id': 41,
  'title': 'non est facere',
  'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'},
 {'userId': 5,
  'id': 42,
  'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas',
  'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'},
 {'userId': 5,
  'id': 43,
  'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis',
  'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'},
 {'userId': 5,
  'id': 44,
  'title': 'optio dolor molestias sit',
  'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'},
 {'userId': 5,
  'id': 45,
  'title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'},
 {'userId': 5,
  'id': 46,
  'title': 'aut quo modi neque nostrum ducimus',
  'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'},
 {'userId': 5,
  'id': 47,
  'title': 'quibusdam cumque rem aut deserunt',
  'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'},
 {'userId': 5,
  'id': 48,
  'title': 'ut voluptatem illum ea doloribus itaque eos',
  'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'},
 {'userId': 5,
  'id': 49,
  'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'},
 {'userId': 5,
  'id': 50,
  'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem',
  'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'},
 {'userId': 6,
  'id': 51,
  'title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'},
 {'userId': 6,
  'id': 52,
  'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'},
 {'userId': 6,
  'id': 53,
  'title': 'ut quo aut ducimus alias',
  'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'},
 {'userId': 6,
  'id': 54,
  'title': 'sit asperiores ipsam eveniet odio non quia',
  'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'},
 {'userId': 6,
  'id': 55,
  'title': 'sit vel voluptatem et non libero',
  'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'},
 {'userId': 6,
  'id': 56,
  'title': 'qui et at rerum necessitatibus',
  'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'},
 {'userId': 6,
  'id': 57,
  'title': 'sed ab est est',
  'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'},
 {'userId': 6,
  'id': 58,
  'title': 'voluptatum itaque dolores nisi et quasi',
  'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'},
 {'userId': 6,
  'id': 59,
  'title': 'qui commodi dolor at maiores et quis id accusantium',
  'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'},
 {'userId': 6,
  'id': 60,
  'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere',
  'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'},
 {'userId': 7,
  'id': 61,
  'title': 'voluptatem doloribus consectetur est ut ducimus',
  'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'},
 {'userId': 7,
  'id': 62,
  'title': 'beatae enim quia vel',
  'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'},
 {'userId': 7,
  'id': 63,
  'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit',
  'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'},
 {'userId': 7,
  'id': 64,
  'title': 'et fugit quas eum in in aperiam quod',
  'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'},
 {'userId': 7,
  'id': 65,
  'title': 'consequatur id enim sunt et et',
  'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'},
 {'userId': 7,
  'id': 66,
  'title': 'repudiandae ea animi iusto',
  'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'},
 {'userId': 7,
  'id': 67,
  'title': 'aliquid eos sed fuga est maxime repellendus',
  'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'},
 {'userId': 7,
  'id': 68,
  'title': 'odio quis facere architecto reiciendis optio',
  'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'},
 {'userId': 7,
  'id': 69,
  'title': 'fugiat quod pariatur odit minima',
  'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'},
 {'userId': 7,
  'id': 70,
  'title': 'voluptatem laborum magni',
  'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'},
 {'userId': 8,
  'id': 71,
  'title': 'et iusto veniam et illum aut fuga',
  'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'},
 {'userId': 8,
  'id': 72,
  'title': 'sint hic doloribus consequatur eos non id',
  'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'},
 {'userId': 8,
  'id': 73,
  'title': 'consequuntur deleniti eos quia temporibus ab aliquid at',
  'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'},
 {'userId': 8,
  'id': 74,
  'title': 'enim unde ratione doloribus quas enim ut sit sapiente',
  'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'},
 {'userId': 8,
  'id': 75,
  'title': 'dignissimos eum dolor ut enim et delectus in',
  'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'},
 {'userId': 8,
  'id': 76,
  'title': 'doloremque officiis ad et non perferendis',
  'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'},
 {'userId': 8,
  'id': 77,
  'title': 'necessitatibus quasi exercitationem odio',

In [37]:
#obtengo la lista de usuarios
url_users = "https://jsonplaceholder.typicode.com/users"

lista_users = requests.get(url_users)
lista_users.json()

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [38]:
#obtengo la lista de tareas
url_tareas = "https://jsonplaceholder.typicode.com/todos"

lista_tareas = requests.get(url_tareas)
lista_tareas.json()

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False},
 {'userId': 1,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'completed': False},
 {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False},
 {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True},
 {'userId': 1,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'completed': False},
 {'userId': 1,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'completed': False},
 {'userId': 1,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'completed': False},
 {'userId': 1,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'completed': True},
 {'userId': 1,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'completed': False},
 {'userId': 1,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'completed': True},
 {'userId': 1,
  'id': 11,
  'title': 'vero rerum temporibus dolor',
  'completed': True},
 {'userId': 1,
  'id': 12,
  'title': 'ipsa repellendus fugit nisi',
  'completed': True},
 {'userId': 1, 'id': 13, 'title': 'et doloremque nulla', 'completed': False},
 {'userId': 1,
  'id': 14,
  'title': 'repellendus sunt dolores architecto voluptatum',
  'completed': True},
 {'userId': 1,
  'id': 15,
  'title': 'ab voluptatum amet voluptas',
  'completed': True},
 {'userId': 1,
  'id': 16,
  'title': 'accusamus eos facilis sint et aut voluptatem',
  'completed': True},
 {'userId': 1,
  'id': 17,
  'title': 'quo laboriosam deleniti aut qui',
  'completed': True},
 {'userId': 1,
  'id': 18,
  'title': 'dolorum est consequatur ea mollitia in culpa',
  'completed': False},
 {'userId': 1,
  'id': 19,
  'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil',
  'completed': True},
 {'userId': 1,
  'id': 20,
  'title': 'ullam nobis libero sapiente ad optio sint',
  'completed': True},
 {'userId': 2,
  'id': 21,
  'title': 'suscipit repellat esse quibusdam voluptatem incidunt',
  'completed': False},
 {'userId': 2,
  'id': 22,
  'title': 'distinctio vitae autem nihil ut molestias quo',
  'completed': True},
 {'userId': 2,
  'id': 23,
  'title': 'et itaque necessitatibus maxime molestiae qui quas velit',
  'completed': False},
 {'userId': 2,
  'id': 24,
  'title': 'adipisci non ad dicta qui amet quaerat doloribus ea',
  'completed': False},
 {'userId': 2,
  'id': 25,
  'title': 'voluptas quo tenetur perspiciatis explicabo natus',
  'completed': True},
 {'userId': 2, 'id': 26, 'title': 'aliquam aut quasi', 'completed': True},
 {'userId': 2,
  'id': 27,
  'title': 'veritatis pariatur delectus',
  'completed': True},
 {'userId': 2,
  'id': 28,
  'title': 'nesciunt totam sit blanditiis sit',
  'completed': False},
 {'userId': 2, 'id': 29, 'title': 'laborum aut in quam', 'completed': False},
 {'userId': 2,
  'id': 30,
  'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis',
  'completed': True},
 {'userId': 2,
  'id': 31,
  'title': 'repudiandae totam in est sint facere fuga',
  'completed': False},
 {'userId': 2,
  'id': 32,
  'title': 'earum doloribus ea doloremque quis',
  'completed': False},
 {'userId': 2, 'id': 33, 'title': 'sint sit aut vero', 'completed': False},
 {'userId': 2,
  'id': 34,
  'title': 'porro aut necessitatibus eaque distinctio',
  'completed': False},
 {'userId': 2,
  'id': 35,
  'title': 'repellendus veritatis molestias dicta incidunt',
  'completed': True},
 {'userId': 2,
  'id': 36,
  'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad',
  'completed': True},
 {'userId': 2, 'id': 37, 'title': 'sunt cum tempora', 'completed': False},
 {'userId': 2, 'id': 38, 'title': 'totam quia non', 'completed': False},
 {'userId': 2,
  'id': 39,
  'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis',
  'completed': False},
 {'userId': 2,
  'id': 40,
  'title': 'totam atque quo nesciunt',
  'completed': True},
 {'userId': 3,
  'id': 41,
  'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit',
  'completed': False},
 {'userId': 3,
  'id': 42,
  'title': 'rerum perferendis error quia ut eveniet',
  'completed': False},
 {'userId': 3,
  'id': 43,
  'title': 'tempore ut sint quis recusandae',
  'completed': True},
 {'userId': 3,
  'id': 44,
  'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis',
  'completed': True},
 {'userId': 3,
  'id': 45,
  'title': 'velit soluta adipisci molestias reiciendis harum',
  'completed': False},
 {'userId': 3,
  'id': 46,
  'title': 'vel voluptatem repellat nihil placeat corporis',
  'completed': False},
 {'userId': 3,
  'id': 47,
  'title': 'nam qui rerum fugiat accusamus',
  'completed': False},
 {'userId': 3,
  'id': 48,
  'title': 'sit reprehenderit omnis quia',
  'completed': False},
 {'userId': 3,
  'id': 49,
  'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et',
  'completed': False},
 {'userId': 3,
  'id': 50,
  'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate',
  'completed': True},
 {'userId': 3,
  'id': 51,
  'title': 'distinctio exercitationem ab doloribus',
  'completed': False},
 {'userId': 3,
  'id': 52,
  'title': 'nesciunt dolorum quis recusandae ad pariatur ratione',
  'completed': False},
 {'userId': 3,
  'id': 53,
  'title': 'qui labore est occaecati recusandae aliquid quam',
  'completed': False},
 {'userId': 3,
  'id': 54,
  'title': 'quis et est ut voluptate quam dolor',
  'completed': True},
 {'userId': 3,
  'id': 55,
  'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione',
  'completed': True},
 {'userId': 3,
  'id': 56,
  'title': 'deleniti ea temporibus enim',
  'completed': True},
 {'userId': 3,
  'id': 57,
  'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia',
  'completed': False},
 {'userId': 3,
  'id': 58,
  'title': 'est dicta totam qui explicabo doloribus qui dignissimos',
  'completed': False},
 {'userId': 3,
  'id': 59,
  'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio',
  'completed': False},
 {'userId': 3,
  'id': 60,
  'title': 'et sequi qui architecto ut adipisci',
  'completed': True},
 {'userId': 4,
  'id': 61,
  'title': 'odit optio omnis qui sunt',
  'completed': True},
 {'userId': 4,
  'id': 62,
  'title': 'et placeat et tempore aspernatur sint numquam',
  'completed': False},
 {'userId': 4,
  'id': 63,
  'title': 'doloremque aut dolores quidem fuga qui nulla',
  'completed': True},
 {'userId': 4,
  'id': 64,
  'title': 'voluptas consequatur qui ut quia magnam nemo esse',
  'completed': False},
 {'userId': 4,
  'id': 65,
  'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni',
  'completed': False},
 {'userId': 4,
  'id': 66,
  'title': 'rerum eum molestias autem voluptatum sit optio',
  'completed': False},
 {'userId': 4,
  'id': 67,
  'title': 'quia voluptatibus voluptatem quos similique maiores repellat',
  'completed': False},
 {'userId': 4,
  'id': 68,
  'title': 'aut id perspiciatis voluptatem iusto',
  'completed': False},
 {'userId': 4,
  'id': 69,
  'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit',
  'completed': False},
 {'userId': 4,
  'id': 70,
  'title': 'ut sequi accusantium et mollitia delectus sunt',
  'completed': False},
 {'userId': 4, 'id': 71, 'title': 'aut velit saepe ullam', 'completed': False},
 {'userId': 4,
  'id': 72,
  'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum',
  'completed': False},
 {'userId': 4,
  'id': 73,
  'title': 'sint amet quia totam corporis qui exercitationem commodi',
  'completed': True},
 {'userId': 4,
  'id': 74,
  'title': 'expedita tempore nobis eveniet laborum maiores',
  'completed': False},
 {'userId': 4,
  'id': 75,
  'title': 'occaecati adipisci est possimus totam',
  'completed': False},
 {'userId': 4, 'id': 76, 'title': 'sequi dolorem sed', 'completed': True},
 {'userId': 4,
  'id': 77,
  'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at',
  'completed': False},
 {'userId': 4,
  'id': 78,
  'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat',
  'completed': False},
 {'userId': 4, 'id': 79, 'title': 'eum ipsa maxime ut', 'completed': True},
 {'userId': 4,
  'id': 80,
  'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur',
  'completed': True},
 {'userId': 5, 'id': 81, 'title': 'suscipit qui totam', 'completed': True},
 {'userId': 5,
  'id': 82,
  'title': 'voluptates eum voluptas et dicta',
  'completed': False},
 {'userId': 5,
  'id': 83,
  'title': 'quidem at rerum quis ex aut sit quam',
  'completed': True},
 {'userId': 5,
  'id': 84,
  'title': 'sunt veritatis ut voluptate',
  'completed': False},
 {'userId': 5, 'id': 85, 'title': 'et quia ad iste a', 'completed': True},
 {'userId': 5,
  'id': 86,
  'title': 'incidunt ut saepe autem',
  'completed': True},
 {'userId': 5,
  'id': 87,
  'title': 'laudantium quae eligendi consequatur quia et vero autem',
  'completed': True},
 {'userId': 5,
  'id': 88,
  'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium',
  'completed': False},
 {'userId': 5, 'id': 89, 'title': 'sequi ut omnis et', 'completed': True},
 {'userId': 5,
  'id': 90,
  'title': 'molestiae nisi accusantium tenetur dolorem et',
  'completed': True},
 {'userId': 5,
  'id': 91,
  'title': 'nulla quis consequatur saepe qui id expedita',
  'completed': True},
 {'userId': 5, 'id': 92, 'title': 'in omnis laboriosam', 'completed': True},
 {'userId': 5,
  'id': 93,
  'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint',
  'completed': True},
 {'userId': 5,
  'id': 94,
  'title': 'facilis modi saepe mollitia',
  'completed': False},
 {'userId': 5,
  'id': 95,
  'title': 'vel nihil et molestiae iusto assumenda nemo quo ut',
  'completed': True},
 {'userId': 5,
  'id': 96,
  'title': 'nobis suscipit ducimus enim asperiores voluptas',
  'completed': False},
 {'userId': 5,
  'id': 97,
  'title': 'dolorum laboriosam eos qui iure aliquam',
  'completed': False},
 {'userId': 5,
  'id': 98,
  'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus',
  'completed': True},
 {'userId': 5,
  'id': 99,
  'title': 'neque voluptates ratione',
  'completed': False},
 {'userId': 5,
  'id': 100,
  'title': 'excepturi a et neque qui expedita vel voluptate',
  'completed': False},
 {'userId': 6,
  'id': 101,
  'title': 'explicabo enim cumque porro aperiam occaecati minima',
  'completed': False},
 {'userId': 6, 'id': 102, 'title': 'sed ab consequatur', 'completed': False},
 {'userId': 6,
  'id': 103,
  'title': 'non sunt delectus illo nulla tenetur enim omnis',
  'completed': False},
 {'userId': 6,
  'id': 104,
  'title': 'excepturi non laudantium quo',
  'completed': False},
 {'userId': 6,
  'id': 105,
  'title': 'totam quia dolorem et illum repellat voluptas optio',
  'completed': True},
 {'userId': 6,
  'id': 106,
  'title': 'ad illo quis voluptatem temporibus',
  'completed': True},
 {'userId': 6,
  'id': 107,
  'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt',
  'completed': False},
 {'userId': 6,
  'id': 108,
  'title': 'a eos eaque nihil et exercitationem incidunt delectus',
  'completed': True},
 {'userId': 6,
  'id': 109,
  'title': 'autem temporibus harum quisquam in culpa',
  'completed': True},
 {'userId': 6, 'id': 110, 'title': 'aut aut ea corporis', 'completed': True},
 {'userId': 6,
  'id': 111,
  'title': 'magni accusantium labore et id quis provident',
  'completed': False},
 {'userId': 6,
  'id': 112,
  'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius',
  'completed': False},
 {'userId': 6,
  'id': 113,
  'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi',
  'completed': False},
 {'userId': 6,
  'id': 114,
  'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae',
  'completed': False},
 {'userId': 6, 'id': 115, 'title': 'sed et ea eum', 'completed': False},
 {'userId': 6,
  'id': 116,
  'title': 'ipsa dolores vel facilis ut',
  'completed': True},
 {'userId': 6,
  'id': 117,
  'title': 'sequi quae est et qui qui eveniet asperiores',
  'completed': False},
 {'userId': 6,
  'id': 118,
  'title': 'quia modi consequatur vero fugiat',
  'completed': False},
 {'userId': 6,
  'id': 119,
  'title': 'corporis ducimus ea perspiciatis iste',
  'completed': False},
 {'userId': 6,
  'id': 120,
  'title': 'dolorem laboriosam vel voluptas et aliquam quasi',
  'completed': False},
 {'userId': 7,
  'id': 121,
  'title': 'inventore aut nihil minima laudantium hic qui omnis',
  'completed': True},
 {'userId': 7,
  'id': 122,
  'title': 'provident aut nobis culpa',
  'completed': True},
 {'userId': 7,
  'id': 123,
  'title': 'esse et quis iste est earum aut impedit',
  'completed': False},
 {'userId': 7, 'id': 124, 'title': 'qui consectetur id', 'completed': False},
 {'userId': 7,
  'id': 125,
  'title': 'aut quasi autem iste tempore illum possimus',
  'completed': False},
 {'userId': 7,
  'id': 126,
  'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe',
  'completed': True},
 {'userId': 7,
  'id': 127,
  'title': 'voluptatem libero consectetur rerum ut',
  'completed': True},
 {'userId': 7,
  'id': 128,
  'title': 'eius omnis est qui voluptatem autem',
  'completed': False},
 {'userId': 7,
  'id': 129,
  'title': 'rerum culpa quis harum',
  'completed': False},
 {'userId': 7,
  'id': 130,
  'title': 'nulla aliquid eveniet harum laborum libero alias ut unde',
  'completed': True},
 {'userId': 7, 'id': 131, 'title': 'qui ea incidunt quis', 'completed': False},
 {'userId': 7,
  'id': 132,
  'title': 'qui molestiae voluptatibus velit iure harum quisquam',
  'completed': True},
 {'userId': 7,
  'id': 133,
  'title': 'et labore eos enim rerum consequatur sunt',
  'completed': True},
 {'userId': 7,
  'id': 134,
  'title': 'molestiae doloribus et laborum quod ea',
  'completed': False},
 {'userId': 7,
  'id': 135,
  'title': 'facere ipsa nam eum voluptates reiciendis vero qui',
  'completed': False},
 {'userId': 7,
  'id': 136,
  'title': 'asperiores illo tempora fuga sed ut quasi adipisci',
  'completed': False},
 {'userId': 7, 'id': 137, 'title': 'qui sit non', 'completed': False},
 {'userId': 7,
  'id': 138,
  'title': 'placeat minima consequatur rem qui ut',
  'completed': True},
 {'userId': 7,
  'id': 139,
  'title': 'consequatur doloribus id possimus voluptas a voluptatem',
  'completed': False},
 {'userId': 7,
  'id': 140,
  'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam',
  'completed': True},
 {'userId': 8,
  'id': 141,
  'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non',
  'completed': True},
 {'userId': 8,
  'id': 142,
  'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut',
  'completed': True},
 {'userId': 8,
  'id': 143,
  'title': 'eum non recusandae cupiditate animi',
  'completed': False},
 {'userId': 8,
  'id': 144,
  'title': 'ut eum exercitationem sint',
  'completed': False},
 {'userId': 8,
  'id': 145,
  'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam',
  'completed': False},
 {'userId': 8,
  'id': 146,
  'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam',
  'completed': True},
 {'userId': 8,
  'id': 147,
  'title': 'eum itaque quod reprehenderit et facilis dolor autem ut',
  'completed': True},
 {'userId': 8,
  'id': 148,
  'title': 'esse quas et quo quasi exercitationem',
  'completed': False},
 {'userId': 8,
  'id': 149,
  'title': 'animi voluptas quod perferendis est',
  'completed': False},
 {'userId': 8,
  'id': 150,
  'title': 'eos amet tempore laudantium fugit a',
  'completed': False},
 {'userId': 8,
  'id': 151,
  'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero',
  'completed': True},
 {'userId': 8,
  'id': 152,
  'title': 'odit eligendi recusandae doloremque cumque non',
  'completed': False},
 {'userId': 8,
  'id': 153,
  'title': 'ea aperiam consequatur qui repellat eos',
  'completed': False},
 {'userId': 8, 'id': 154, 'title': 'rerum non ex sapiente', 'completed': True},
 {'userId': 8,
  'id': 155,
  'title': 'voluptatem nobis consequatur et assumenda magnam',
  'completed': True},
 {'userId': 8,
  'id': 156,
  'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis',
  'completed': True},
 {'userId': 8,
  'id': 157,
  'title': 'dolorem veniam quisquam deserunt repellendus',
  'completed': True},
 {'userId': 8,
  'id': 158,
  'title': 'debitis vitae delectus et harum accusamus aut deleniti a',
  'completed': True},
 {'userId': 8,
  'id': 159,
  'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis',
  'completed': True},
 {'userId': 8,
  'id': 160,
  'title': 'et praesentium aliquam est',
  'completed': False},
 {'userId': 9,
  'id': 161,
  'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa',
  'completed': True},
 {'userId': 9,
  'id': 162,
  'title': 'omnis laboriosam molestias animi sunt dolore',
  'completed': True},
 {'userId': 9,
  'id': 163,
  'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit',
  'completed': False},
 {'userId': 9,
  'id': 164,
  'title': 'reprehenderit quos aut aut consequatur est sed',
  'completed': False},
 {'userId': 9,
  'id': 165,
  'title': 'fugiat perferendis sed aut quidem',
  'completed': False},
 {'userId': 9,
  'id': 166,
  'title': 'quos quo possimus suscipit minima ut',
  'completed': False},
 {'userId': 9,
  'id': 167,
  'title': 'et quis minus quo a asperiores molestiae',
  'completed': False},
 {'userId': 9,
  'id': 168,
  'title': 'recusandae quia qui sunt libero',
  'completed': False},
 {'userId': 9,
  'id': 169,
  'title': 'ea odio perferendis officiis',
  'completed': True},
 {'userId': 9,
  'id': 170,
  'title': 'quisquam aliquam quia doloribus aut',
  'completed': False},
 {'userId': 9,
  'id': 171,
  'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio',
  'completed': True},
 {'userId': 9,
  'id': 172,
  'title': 'et provident amet rerum consectetur et voluptatum',
  'completed': False},
 {'userId': 9,
  'id': 173,
  'title': 'harum ad aperiam quis',
  'completed': False},
 {'userId': 9, 'id': 174, 'title': 'similique aut quo', 'completed': False},
 {'userId': 9,
  'id': 175,
  'title': 'laudantium eius officia perferendis provident perspiciatis asperiores',
  'completed': True},
 {'userId': 9,
  'id': 176,
  'title': 'magni soluta corrupti ut maiores rem quidem',
  'completed': False},
 {'userId': 9,
  'id': 177,
  'title': 'et placeat temporibus voluptas est tempora quos quibusdam',
  'completed': False},
 {'userId': 9,
  'id': 178,
  'title': 'nesciunt itaque commodi tempore',
  'completed': True},
 {'userId': 9,
  'id': 179,
  'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo',
  'completed': True},
 {'userId': 9,
  'id': 180,
  'title': 'debitis nisi et dolorem repellat et',
  'completed': True},
 {'userId': 10,
  'id': 181,
  'title': 'ut cupiditate sequi aliquam fuga maiores',
  'completed': False},
 {'userId': 10,
  'id': 182,
  'title': 'inventore saepe cumque et aut illum enim',
  'completed': True},
 {'userId': 10,
  'id': 183,
  'title': 'omnis nulla eum aliquam distinctio',
  'completed': True},
 {'userId': 10,
  'id': 184,
  'title': 'molestias modi perferendis perspiciatis',
  'completed': False},
 {'userId': 10,
  'id': 185,
  'title': 'voluptates dignissimos sed doloribus animi quaerat aut',
  'completed': False},
 {'userId': 10,
  'id': 186,
  'title': 'explicabo odio est et',
  'completed': False},
 {'userId': 10,
  'id': 187,
  'title': 'consequuntur animi possimus',
  'completed': False},
 {'userId': 10, 'id': 188, 'title': 'vel non beatae est', 'completed': True},
 {'userId': 10,
  'id': 189,
  'title': 'culpa eius et voluptatem et',
  'completed': True},
 {'userId': 10,

También se podría hacer todo en una sola celda guardando los resultados en una variable e imprimir solo 2 ejemplos de cada

In [39]:
#solución e nuna misma celda

url_publicaciones = "https://jsonplaceholder.typicode.com/posts"

lista_posts = requests.get(url_publicaciones)
publicaciones = lista_posts.json()

url_usuarios = "https://jsonplaceholder.typicode.com/users"
lista_usuarios = requests.get(url_users)
users = lista_usuarios.json()

url_tareas = "https://jsonplaceholder.typicode.com/todos"
lista_tasks = requests.get(url_tareas)
tareas = lista_tasks.json()

print("primeras 2 publicaciones: ")
print(publicaciones[:2])
print("primeros 2 usuarios: ")
print(users[:2])
print("primeras 2 tasks: ")
print(tareas[:2])

primeras 2 publicaciones:
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}]
primeros 2 usuarios:
[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}]
primeras 2 tasks:
[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}]

Muestra por pantalla:

- La cantidad total de cada recurso
- El código de estado de cada petición

In [40]:
#Al tratarse de una lista de Python, se puede usar la función integrada len() para saber el total de cada recurso
publicaciones = lista_publicaciones.json()
usuarios = lista_users.json()
tasks = lista_tareas.json()
print(f"La cantidad de publicaciones total son: {len(publicaciones)}")
print(f"La cantidad de usuarios totales son: {len(usuarios)}")
print(f"la cantidad de tareas totales son: {len(tasks)}")

La cantidad de publicaciones total son: 100
La cantidad de usuarios totales son: 10
la cantidad de tareas totales son: 200

In [41]:
#muestro el código de estado de cada petición
publi = lista_publicaciones.status_code
usu = lista_users.status_code
tar = lista_tareas.status_code
print(f"El código de estado de la petición de publicaciones es: {publi} ")
print(f"El código de estado de la petición de usuarios es: {usu} ")
print(f"El código de estado de la petición de tareas es: {tar}")

El código de estado de la petición de publicaciones es: 200
El código de estado de la petición de usuarios es: 200
El código de estado de la petición de tareas es: 200

El código 200 muestra que la solicitud fue reconocida por el servidor, aceptada y está siendo procesada

Haz una petición a una publicación inexistente para obtener un error 404 y muestre el código de estado recibido

In [42]:
#petición a una publicación inválida
post_url = ("https://jsonplaceholder.typicode.com/posts/300")
response = requests.get(post_url)
print(response)

<Response [404]>

En este caso, como sabemos que el recurso  /posts tiene 100 registros, en la url, debemos apuntar directamente al identificador que queremos que nos muestre por pantalla. En este caso, hemos pasado el 300 (inexistente), es por ello que arroja el error 404 "not found", la url no existe.

Haz una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

- Muestra la respuesta JSON
- Muestra el código de estado

In [43]:
#creación de una nueva publicación ficticia
publi_url = "https://jsonplaceholder.typicode.com/posts/"

datos = {#añado los datos que quiero añadir a la publicación en formato diccionario clave : valor
    "title" : "my first post",
    "body" : "Hello from Python!",
    "userId" : 12
}

response = requests.post(publi_url, json=datos) #paso el resquests POST y serializo los datos con json
print(f"Respuesta JSON: {response.json()}")#muestro por pantalla los resultados en formato json
print(f"Estatus: {response.status_code}")

Respuesta JSON: {'title': 'my first post', 'body': 'Hello from Python!', 'userId': 12, 'id': 101}
Estatus: 201

Añado los datos ficticios que quiero introducir mediante un diccionario de Python (clave : valor). Paso el requests POST, la url y los datos creados en formato JSON y muestro por pantalla.
El resultado del código de estado obtenido es 201. La serie de códigos 200 indican que la solicitud fue reconocida por el servidor, aceptada y está siendo procesada.
El código 201 significa "creado" La solicitud se cumplió y el servidor creó un nuevo recurso.

Haz una petiicón PATCH para modificar parcialmente una publicación existente.

- Muestra la respuesta JSON
- Muestra el código de estado

In [44]:
#En este caso, vamos a modificar parcialmente una publicación existente, concretamente, el titulo
modificacion_url = "https://jsonplaceholder.typicode.com/posts/1"#uso la url apuntando al id 1 (primer publicación)

datos_modificados = {
    "title" : "my post has been modified"#le digo qué datos quiero modificar, en este caso el titulo y le digo qué quiero poner en el diccionario python
}

response = requests.patch(modificacion_url, json=datos_modificados)#uso el requests patch para modificar parcialmente la entrada, le paso la url y serializo los datos
print(f"Respuesta JSON: {response.json()}")#muestro los datos
print(f"Estatus: {response.status_code}")

Respuesta JSON: {'userId': 1, 'id': 1, 'title': 'my post has been modified', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Estatus: 200

Haz una petición DELETE sobre una publicación.

- Muestra la respuesta JSON
- Muestra el código de estado

In [45]:
#en este caso, vamos a eliminar la quinta publicación
eliminacion_url = "https://jsonplaceholder.typicode.com/posts/5"#apunto a la quinta posición

response = requests.delete(eliminacion_url)
print(f"Respuesta JSON: {response.json()}")
print(f"Estatus: {response.status_code}")

Respuesta JSON: {}
Estatus: 200

Vemos que la respuesta es un diccionario vacío, ya que hemos eliminado la publicación número 5. El estatus que muestra es 200 (procesada). En ocasiones también puede sacar estatus 204 "no content", puesto que ha sido eliminada.

**Nivel 2**

  Explora el repositorio de Public APIs y escoge una API que permita hacer peticiones GET.

In [46]:
url_api1 = "https://blockchain.info/latestblock"

response1 = requests.get(url_api1)
response1.json()

{'hash': '0000000000000000000040898fe3efc9d6d6b27de1fbe3b231ecf7046293faca',
 'time': 1787848386,
 'block_index': 964323,
 'height': 964323,
 'txIndexes': [695966919965635,
  6751179972774911,
  4827173109721259,
  7992044013347608,
  7594700067538972,
  7448817398954901,
  6933421418703247,
  5098997404279742,
  6919830440550699,
  428361553049544,
  6233788072812035,
  7234742418267624,
  8585076892542027,
  1894045886367380,
  4769707225193197,
  6107024861289824,
  6178758285367815,
  7854184825337085,
  7714472476716739,
  7487978502062666,
  4111707145621677,
  7500448249834899,
  581618014090477,
  6926204237876521,
  4009407251492127,
  5751530883730962,
  6858495539073548,
  5694646600719286,
  5419271489798143,
  7536190193341809,
  4933047380716701,
  5622253395084272,
  1199960890288063,
  8304132903334764,
  8142211148132561,
  3930937494324961,
  4305448594716682,
  2474824860630538,
  2149150629151313,
  2232248005858890,
  2389579487510361,
  3855520033775614,
  4552918706764264,
  4727898648638420,
  6112818829968349,
  7971965513137752,
  8132924067151440,
  6806619702976947,
  5046940552362721,
  4823598326114974,
  8158845255467840,
  4221046714116224,
  4280214633097340,
  7420545737372794,
  7064827830584547,
  1220434817460983,
  1527745410847106,
  3321893110250535,
  1493151108564193,
  8491588003406820,
  8685923699227501,
  2328875287411100,
  5250548555209891,
  1717538974228714,
  6335584622631312,
  3613582437169115,
  8133498864177433,
  7330105277443590,
  211078039040273,
  956052615725598,
  1378414710104016,
  2669425260663039,
  3143853376918837,
  3821223556096934,
  5146567460859016,
  6738863637994917,
  7154458617892655,
  7483740540127209,
  7526933650871662,
  8361166783694987,
  8507821656469931,
  8886527635786167,
  1197377565085255,
  2290727392460541,
  2734551157154095,
  825595743610436,
  7560701500570615,
  3743251128341918,
  1829520340514572,
  3114507139313717,
  2313893830196031,
  8765716328301684,
  1231225521194028,
  1165925429266961,
  4419626065328766,
  6587684695320434,
  6805968686702490,
  7877589949102387,
  3786334382869806,
  1496485445122491,
  4050369829800563,
  6699382098066439,
  483739823654150,
  5562961980480601,
  8995836543358516,
  1988800042427183,
  3721318609732501,
  5064861394237826,
  6655128204259024,
  43429880688000,
  6130844765114944,
  7039349704058295,
  855622693794359,
  5047399867325412,
  2775795028989476,
  6737280729575010,
  4796915512297676,
  712532986402156,
  6204728503641275,
  6864393205335954,
  8580407891997844,
  7197391359239464,
  303806527686153,
  1529450635946699,
  5430983962464086,
  6428316870992217,
  3244552041435783,
  6340470990556973,
  7022841121783834,
  2254244319359129,
  5669673865896112,
  1679684274182441,
  7425549777505185,
  1389833044618991,
  1575127580044115,
  1824490527313116,
  1878795143993096,
  3149967100237066,
  6145483863703922,
  8750312763316472,
  8893550947686554,
  6949998184644753,
  7970688385812533,
  2078964111720122,
  4575141462370903,
  715905537941535,
  1177458023281511,
  4399420145864536,
  8275359459848386,
  2002751473875235,
  5003590177436574,
  256228838271275,
  307439003135541,
  1337667949980597,
  1731601977653402,
  2330981913500605,
  2486980342462940,
  3095753495992627,
  3447988998422392,
  4216038196093922,
  4558583096624148,
  4735558104863789,
  5051406930528484,
  5888024066511604,
  6124357923943060,
  6240369277209176,
  6359829392976891,
  6426473749458919,
  7309006171405228,
  7492034842431149,
  8151368646465181,
  8774253080779541,
  2947578111197178,
  1562932100420824,
  4473609214616051,
  4648308159113784,
  7090998714874313,
  1199636636870559,
  3010161353626498,
  4453093193245944,
  5982097629607496,
  7734062665688311,
  8637271258531289,
  1055743586729231,
  1409923063202967,
  3971237944223387,
  2490191212223758,
  2857710180780691,
  5561840814046451,
  8405677378152083,
  6300399096696738,
  7466043686795492,
  315042919590822,
  2462015448191345,
  3158662315545301,
  7614684115550143,
  526079769661594,
  4437846669462745,
  5613628715645041,
  7406718394990414,
  813202366171830,
  1400331575610104,
  3430892097491034,
  145778090970013,
  2213781018899839,
  8658169546461647,
  6247943061152623,
  3876930259332511,
  8251595730884713,
  2896608421139719,
  8695461602599599,
  4187181310732894,
  7936078321644420,
  1211104442708657,
  3648949485299557,
  386991420093938,
  3985331017055351,
  8376294835106340,
  571896467087782,
  809167471609007,
  525238980780600,
  5467325170496003,
  8542704381256498,
  8291764046532464,
  7061343782430997,
  1794285199060419,
  2773275073658165,
  4655004763048676,
  6434512813716994,
  5430734198912179,
  4945867117076803,
  1970464959447965,
  3465040797392549,
  8813986154078941,
  5388672343474931,
  6779717972784994,
  3298043353776627,
  8819579667578305,
  6343359286562096,
  5494601653417381,
  5574514746435713,
  6686152831020606,
  8931600616723740,
  3014494531542841,
  1727959456829354,
  113882634889442,
  140375673906839,
  153959151803985,
  390529931263526,
  442428382415226,
  458583020357137,
  514935592360373,
  568013668590215,
  571756500451023,
  643006487039704,
  662432506164406,
  728411755197664,
  743062272881920,
  930295309551322,
  1012767739746559,
  1035031925110309,
  1073331468018191,
  1161674675035540,
  1210509315541712,
  1242832007208074,
  1335995572987966,
  1348600949280842,
  1360737365279929,
  1366606535289808,
  1368619770124159,
  1385313147980291,
  1448650394357646,
  1535159347357087,
  1681345923824763,
  1696984516790435,
  1701570471990559,
  1720047504132141,
  1964478031002533,
  1970587323771381,
  2197173060972368,
  2209909938283009,
  2270812223371531,
  2442810657850296,
  2450201899252792,
  2473329041772278,
  2473467767186045,
  2554214151936064,
  2577604586628281,
  2649261171465778,
  2664037653741052,
  2738061342785844,
  2750963788605214,
  2825064690960325,
  2904484481838621,
  2988023424003800,
  3048515368721824,
  3196561281167174,
  3399125120880833,
  3500926962648201,
  3530056235767016,
  3597768921236779,
  3973572033056623,
  4033458129540724,
  4094282311098286,
  4241323724305961,
  4252049232100714,
  4293150662110008,
  4401928095779002,
  4446028759388952,
  4469765156365906,
  4530310238045665,
  4604628158952966,
  4682707595957714,
  4703858118593994,
  4733536817058879,
  4778342771945478,
  4805293054240179,
  4830032704325607,
  4850729985639099,
  4967981769348761,
  5008243606411948,
  5096174165488723,
  5127430835756602,
  5284209553946200,
  5368451327284143,
  5423020125303832,
  5507548076113111,
  5529588054276425,
  5561645748443247,
  5568360626616825,
  5670174556682787,
  5864330074975738,
  5977895442571396,
  6013844153314268,
  6045367355215475,
  6071780034551647,
  6076632449052955,
  6095118805628086,
  6204985999134431,
  6294429549012206,
  6327366033684930,
  6441072602369972,
  6480147292173269,
  6553590951307550,
  6591447802340904,
  6689399118506233,
  6739953809900878,
  6790644313926098,
  6835076107155256,
  6881347619775540,
  6926357137024330,
  6929069382400139,
  6974034434067097,
  7010511313948180,
  7036001473856211,
  7054938154053336,
  7067827914473892,
  7080630788249391,
  7105987588049977,
  7120535127921999,
  7190697264378657,
  7224116807035306,
  7230231907838918,
  7270257127062315,
  7370197182241081,
  7374116924637943,
  7382310202577950,
  7546098078517344,
  7629955291138944,
  7722716054085922,
  7874968808858912,
  7992167175985511,
  8053758024517538,
  8055255559801682,
  8144251238180304,
  8198602778473898,
  8467988232395986,
  8497066682196285,
  8823322766948727,
  8831070182990103,
  8838190384817283,
  8858888779375218,
  8913668269385618,
  8933303980178260,
  8941273043600303,
  8962999145739197,
  8991956904758931,
  9005092461806738,
  886521495583147,
  3150334178473667,
  1245086314584524,
  6849591792597855,
  5239740576564082,
  6282017963607315,
  3907786797031765,
  1769547559919658,
  4174396390418005,
  4294194246899023,
  495708797523276,
  1821894166636091,
  1551059715387603,
  6973775580742962,
  1140468828271289,
  1228769173071095,
  5922062480653713,
  6267835648364767,
  2042823919390975,
  4620996110273085,
  7298356306279944,
  5455589331015113,
  1606418330081821,
  6984562217577330,
  5073089148314322,
  3099810985035099,
  1007271104706749,
  3159519424374400,
  141320199558555,
  4862712251805455,
  8181415595994103,
  5337509775288067,
  8534108384114137,
  6704495431602988,
  5640594422811506,
  517980454368739,
  4438535587830457,
  5304077673366138,
  4286689684574371,
  2536160995557536,
  2611926936263605,
  2479794373370224,
  3532025694771186,
  2070346885896654,
  3346755382534845,
  4220362269936088,
  2947565848713996,
  4263927547757898,
  4591392139334588,
  1982138244261375,
  4155065489101503,
  8073991422223998,
  5947321982646456,
  4653418122981963,
  2862413190332807,
  5064547864229897,
  327438090988454,
  3963090330743355,
  5513042560945806,
  6177599134168706,
  6930811243950688,
  612210824539972,
  5066125656214037,
  7966035335046013,
  6125634565156424,
  784762865997324,
  7319028440126314,
  7669539317932488,
  1143400139204116,
  4674018145839633,
  6669953917920661,
  3629259703280560,
  3907279731242574,
  5333428741307926,
  6708886206036308,
  314654192302120,
  1417188835369598,
  7141452578856829,
  2830279024463691,
  2390146662905378,
  4233753122304675,
  8355931566613883,
  2014443705046237,
  6113219432638087,
  2033721637177528,
  5353713180251836,
  6151830310248986,
  2367918735245321,
  946796605554392,
  8511963362597751,
  2580059673743135,
  6295036240326418,
  577116470507506,
  709054125670587,
  1223425250336894,
  4283401623814609,
  5762423681454003,
  8737431338569536,
  4864455575453997,
  2183243931046978,
  4657409620658651,
  6657835651834440,
  6433661296342726,
  1817524320110447,
  2349924316629671,
  1637267118807902,
  5605588256424426,
  1401556472143503,
  6200013385599238,
  2803226240047137,
  6809673915033266,
  331420141509259,
  426379129323751,
  426910804057459,
  485949785848934,
  500858535171350,
  712793438411360,
  756921642598408,
  1099819500724305,
  1107183056479931,
  1129578133947139,
  1195043933226592,
  1201789039658262,
  1249514736105362,
  1316713062724919,
  1323636290745972,
  1568584753719848,
  1593618446762369,
  1683101187053028,
  1742760145154819,
  1774437074879865,
  2048660073707835,
  2061150927899987,
  2102318621962252,
  2259857032342778,
  2276979543502824,
  2335862972047654,
  2381597508460862,
  2452173619250397,
  2573938972240163,
  2668625500445386,
  2724875415612816,
  2799319670562512,
  2826124641531961,
  2829635773104149,
  2835068842163720,
  3039844427172795,
  3129677960331982,
  3187113881971174,
  3695829804319666,
  3540394936371464,
  3663040681939077,
  3873864066564730,
  3927647924021571,
  4015167114969930,
  4054553568753227,
  4128259537400979,
  4325901571685096,
  4359086900005480,
  4436521571387947,
  4495927815226846,
  4539774049305335,
  4732030927477824,
  4734126306051898,
  4824384320097241,
  4991797173261541,
  4999291079009447,
  5237445585862434,
  5425314936447188,
  5505742363322991,
  5530054422361931,
  5658409584573332,
  5808696360226679,
  5857072928273291,
  6031567108541951,
  6093211069328789,
  6116993247944436,
  6127044506804409,
  6195888069623760,
  6337456251748500,
  6470376823570010,
  6628975513714244,
  6675721214415007,
  6825687754610493,
  7015142705860153,
  7267908307927430,
  7583565291411024,
  8014670638329102,
  8382392299432932,
  8469339537405646,
  8549829273552953,
  8716774507429475,
  8873835422101949,
  642638186540279,
  7960369964157104,
  1738687446264525,
  6325463831346233,
  6075923047846628,
  7167313755292520,
  4111034213312958,
  6830170016115703,
  196277331928677,
  87465640534162,
  4255636225212806,
  4063043453707861,
  2126080979695760,
  8019185330105340,
  6408099999263940,
  2739413788987357,
  1332646372868395,
  5492721764942769,
  5402319119480241,
  5932489054638892,
  8186191225870238,
  1472017627286713,
  5127078335897784,
  1038780166479778,
  1449543634188724,
  4197660235212763,
  2691914359763984,
  7813524436440141,
  6722249006203140,
  1871952334866959,
  639863923948787,
  6752433189644101,
  2541722906053218,
  3929712881217033,
  2513112447798613,
  2331145107200725,
  3541329710778790,
  8684145304208248,
  4117310382114974,
  1742877153186943,
  5316256970221320,
  4303425274649894,
  4064077195790238,
  1686754274476232,
  5030236666543611,
  1615317854785617,
  4943319453110612,
  4302244613194247,
  510590257333891,
  3826051194536184,
  5516998550699393,
  5546822323198842,
  7145444184528959,
  2852402246382077,
  5750080700249383,
  4497936929859866,
  614669556161199,
  1528568985391677,
  930954281228441,
  6411579207900627,
  4227953577714912,
  8314494640325869,
  4140494687170377,
  3604175638413481,
  311446807364631,
  5869736755605229,
  6290950553515301,
  8648928565010528,
  7155579843626999,
  5211543250409296,
  5761016053961266,
  2268300360191943,
  3270417389618179,
  3463473243882420,
  6811741399648672,
  646167905527330,
  3096415342333764,
  1954255630594554,
  5406399557136434,
  2259232537735229,
  5844378825476112,
  6631990101928137,
  6852506803345420,
  7302805057430877,
  8642853797442267,
  8205258502391443,
  145338075278622,
  3151042540065833,
  7784015496182173,
  5901620296073207,
  365891248778204,
  485080102290021,
  803222173078502,
  1011261536242919,
  1070653737553079,
  1135187039695854,
  1145133200782464,
  1464416528331788,
  1480491592127434,
  1482775329212142,
  1655629851677238,
  1891526548869615,
  1961056855989629,
  2183287301302980,
  2428280584003135,
  3353405624187930,
  3434809910321653,
  3704509071104404,
  3775092177664868,
  3876166694662487,
  4517807994504228,
  4533819471218917,
  4784295774066932,
  4873752197837987,
  5012575246739019,
  5194484487011290,
  5286627298506177,
  5494579661668634,
  5561797376030256,
  5784432289622306,
  5957884123923143,
  5973340607162030,
  6017388025939465,
  6142377148120546,
  6340397888312140,
  6383617504979890,
  6499674341365472,
  6685666502986293,
  7276809502552118,
  7334550741429986,
  7371403831187343,
  7449924876406409,
  7959130795725589,
  8325976608999997,
  8329203457437248,
  8590567057592201,
  8684903706149438,
  8975851216138525,
  252906202308399,
  749212857762247,
  5108440202713314,
  5263534422788886,
  6601772553871882,
  7181253843516581,
  7677217821925124,
  4940815082829577,
  1600575525004685,
  2119769980549870,
  3580227723943180,
  8165088434972905,
  5939145482843265,
  4233585573070616,
  6394884836814149,
  7336983800589912,
  4911773691699749,
  2355591897839342,
  2564338978815897,
  5306111547838340,
  241030760400303,
  318131102390608,
  382853699599326,
  415242377050030,
  565481219922155,
  652767422535984,
  972843687714089,
  1175364944306592,
  1270793729736252,
  1361105199336519,
  1405961772413729,
  1551893975520522,
  1636761036350177,
  3823157876660252,
  1722581097431995,
  2037054714379674,
  2127950846171736,
  2292800294233033,
  2435862520895684,
  2621489544771685,
  2650900908972813,
  2702600311991490,
  2743714494995335,
  2853787283510694,
  2866700104669842,
  2908982342748071,
  3211575988951827,
  3465467484484017,
  3498894879364412,
  3643401188684448,
  3812800580319292,
  4517010446377744,
  4600571038166061,
  4675846260200735,
  4887622149106409,
  4912922894267359,
  5037746051846275,
  5113470727864490,
  5202641049886770,
  5293504844350342,
  5355832697883172,
  5399426919938722,
  5437288770404979,
  5452792125971034,
  5464150601516766,
  5465964260660254,
  5498634345928082,
  5669542580153313,
  5692499227862749,
  5708719855833912,
  5747171682935276,
  5776013687200319,
  5796924892253699,
  6572522677913018,
  5910195920892269,
  5922351628617728,
  5947357025375978,
  5993372755392677,
  6134977721430688,
  6240612852036831,
  6595204588782970,
  6698668426460466,
  6973087043970192,
  7153018900026593,
  7184224859955172,
  7220537490421908,
  7246371666451776,
  7336423293852863,
  7374237020432357,
  7435955423623088,
  7614150102955424,
  7809745675136306,
  7839529597208419,
  7923386967200340,
  7986683217973045,
  8021993650622954,
  8067171210590270,
  8169271313074023,
  8280809205251009,
  8411951657183757,
  8825166967538766,
  8947034990580541,
  8789907322150602,
  6797999958219279,
  7650532639441645,
  3987338339743074,
  932760985358821,
  1195350087422307,
  1226495374117708,
  1376848013557230,
  4308807177415667,
  4909349330982707,
  6606268206721609,
  6914759190969571,
  7219331846863942,
  7318587830353173,
  8261933296254778,
  3708902248415884,
  2306263692921251,
  2756844205986780,
  4680024948816220,
  6510522143390603,
  7510256002683795,
  7950530352175180,
  91239622177104,
  604950558840997,
  1227482995344438,
  1228207746293020,
  2219053649393449,
  3148640094686894,
  3502237248202293,
  5139364649538448,
  5379840214064442,
  5408812690543642,
  5648215062213115,
  6376980883400757,
  6462573991230129,
  6568850785233517,
  6837410563442326,
  6993727014892003,
  7440862953132609,
  7525760016279465,
  7836170847467580,
  8118530681396237,
  1902934426304156,
  3629807411647680,
  273845471806072,
  1642162785384655,
  8282656126478748,
  1130971572279045,
  2034645626594536,
  1722073151638094,
  6527794713481340,
  5116237262775220,
  7792552912390423,
  6675170624179216,
  1910474185402823,
  1833390901528404,
  1993887765492667,
  3032646784952880,
  6396348071855671,
  7314608137895767,
  7575530787263051,
  133392513257836,
  352741621430224,
  725161459692405,
  1063237574016645,
  1779874456897327,
  2559121842456104,
  3204304161671989,
  3637752119070776,
  3654165384629519,
  4162203585874058,
  4295648582843544,
  4360249281239953,
  4765059281675579,
  4922405758217753,
  5217041098433889,
  5826626357456957,
  6113243815883231,
  6818823259614131,
  7073262646110526,
  7299830272788569,
  7962840454715554,
  8013531693877052,
  8259119654531335,
  3506648754976699,
  4829420132963906,
  2259483511091177,
  3764937890552723,
  4740706270457999,
  5681929724561009,
  8190729423844897,
  589388636399496,
  6178012057798965,
  6089044391247082,
  4225721974255378,
  5249964735471993,
  6058576152764371,
  7913895165182934,
  375675400098362,
  896369164226431,
  1503339555091454,
  1513352161973291,
  1750617002468968,
  1795123243594831,
  2277951900205079,
  2589729642721771,
  3041018243782113,
  3069857314883112,
  3610889761523303,
  3703308771446201,
  4549721691463107,
  4596093440067612,
  6087726577804929,
  7938862115640079,
  8614782264490589,
  8631035796495868,
  8783109505297275,
  9000244072600937,
  6621606704554888,
  133783307543495,
  4084705702820681,
  5170643915470809,
  7619958535949404,
  3410167708842001,
  7236205199457149,
  867050312762791,
  7489872322178600,
  7072121638980387,
  5283156829207260,
  8381951484785924,
  1924088281427352,
  6816938553929788,
  6946162444922733,
  7318537110557278,
  4217518107120002,
  3637054539038313,
  8191918094994400,
  4006553162838469,
  5670104694812897,
  7351454837288101,
  1745514460023839,
  1708645195015615,
  2791824456873545,
  6038114773931025,
  3468936441165410,
  6326633380423166,
  8733737303496698,
  213074748300576,
  3613123586291545,
  4575179538724312,
  3528951035904432,
  7284666026112336,
  52150514487842,
  609333853333989,
  3269202439726842,
  4861554342556261,
  4216727648018542,
  7340891372718020,
  5681126008376894,
  5826738491222515,
  735097773123817,
  6680787270369029,
  7289194431846645,
  6495558037944269,
  8200233528494844,
  8735805123813262,
  6235015493950778,
  7809831759368582,
  182999605779873,
  1843847409946725,
  5438159005906293,
  8019174396084688,
  7700973194003039,
  6093230965174042,
  6112754876097239,
  8013341829751364,

In [47]:
url_api2 = "https://blockchain.info/unconfirmed-transactions?format=json"

response2 = requests.get(url_api2)
response2.json()

{'txs': [{'hash': 'bf9e410013a4ffc8a9e0bbe95f2be1d92ab1831df37b003d92fa6a053b8d80e4',
   'ver': 1,
   'vin_sz': 1,
   'vout_sz': 2,
   'size': 222,
   'weight': 561,
   'fee': 278,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 8039704844873055,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967293,
     'witness': '0247304402200e5e6ed951771b35f1421b148b77dba2de10fa117386203ece6befc10b819ad70220272d2327481455f842c59067bea0ac23f3ef1d339cd4eff242eb83d06907e3440121034013c567349250bf27450a870c24c47078fcd8b11512c05c2bb8774bc99373bb',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 29619,
      'spending_outpoints': [{'tx_index': 8039704844873055, 'n': 0}],
      'n': 0,
      'tx_index': 6920284783195131,
      'script': '0014bfb0ceed3d20c419befd24fab974b5f181313ca5',
      'addr': 'bc1qh7cvamfayrzpn0haynatja947xqnz099el89hu'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 683,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 8039704844873055,
     'script': '00145275aa611985bb83eb5c07d3f124530a94c75cca',
     'addr': 'bc1q2f665cgeskac866uqlflzfznp22vwhx2ece7t9'},
    {'type': 0,
     'spent': False,
     'value': 28658,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 8039704844873055,
     'script': '00141af4a2cbf0a954f590e152ee0edcac2ec0d3ec1e',
     'addr': 'bc1qrt629jls4920ty8p2thqah9v9mqd8mq7fjf7hr'}],
   'rbf': True},
  {'hash': '94268a34bb0c777b226952d7984549cd93fd1a32324b4fc89056435060371cd7',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 2,
   'size': 225,
   'weight': 573,
   'fee': 322,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 7568518019680362,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967293,
     'witness': '024730440220751faf9a667df1b4692075c32d274ca906de5887910337b1bf2b8a7622f7137302205d72f7f07d2d2102b61c708baab190f3d591200b1665ecf32d0626e0736d04e30121027aebbc15bedba8785a947f00cde12f6128dcc5fa40d151f9e7635cb2e687ebcf',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 521663,
      'spending_outpoints': [{'tx_index': 7568518019680362, 'n': 0}],
      'n': 0,
      'tx_index': 1232654863526218,
      'script': '00147ef1896fdf6f11a781e583a7f380e2e43fd980f8',
      'addr': 'bc1q0mccjm7ldug60q09swnl8q8zuslanq8cxp2gaa'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 477683,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 7568518019680362,
     'script': '00147ef1896fdf6f11a781e583a7f380e2e43fd980f8',
     'addr': 'bc1q0mccjm7ldug60q09swnl8q8zuslanq8cxp2gaa'},
    {'type': 0,
     'spent': False,
     'value': 43658,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 7568518019680362,
     'script': '76a914fa957b5d007c0e078976c443c477369a34244a6988ac',
     'addr': '1Pqy19CBSxp4m4p978fDjyHa97VRPQLDKe'}],
   'rbf': True},
  {'hash': 'b4652f5f66328ce6d4b24c18f020016d58bba93c1fb3f008c173dd7a9003c6a3',
   'ver': 1,
   'vin_sz': 11,
   'vout_sz': 2,
   'size': 1708,
   'weight': 3277,
   'fee': 3412,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 5762267476876206,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967295,
     'witness': '02483045022100e3e6386e17fb88faea94968ef9ce60b138636eb000ab6fdfaa46ad9898da1ce4022022b4604fb0cdd2c028a23352aa74ecf10b2afdd7e89c2a81d77c64d29c8fd30281210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 30000000,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 0}],
      'n': 0,
      'tx_index': 5574514746435713,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '0247304402200e41ca12072c7123c06aacf0043f2bb037eefeddd9cf7b42a49165842d7e6f3802200d18ce3bdfe7872bb94f4ad47bed8ffbc38835ef0afb6e21eb8bd84ea4cfe66381210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 1,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 14806900,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 1}],
      'n': 0,
      'tx_index': 3971237944223387,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '02483045022100bd165becd9e576a3e9bd4608ef4d5d361992cf00f8a606ecd3dd3694b2f788290220188c74c215e31fb97a770558a0e21e8a6feee91cdd412224abee5959b396d3fb81210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 2,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 6108882,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 2}],
      'n': 0,
      'tx_index': 6686152831020606,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '02483045022100bc70d594bf5069b93247a14f47e06e6ef88e474b443796f59a23884c75491a84022063cc6862fcc875dded1189f4e4f43ce5c0cd8fa6fc92888fbbb1c46d48471b2f81210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 3,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 93265286,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 3}],
      'n': 0,
      'tx_index': 3465040797392549,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '02483045022100912285c0a480a919e241af69f02ff63b8285173ba8cff0e8d9568062ab159d3b022043ca525b7cbcc5629950ecfbd0cf5716a0e1a73158baf8d348bca3322109088f81210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 4,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 222840573,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 4}],
      'n': 1,
      'tx_index': 8692933512033044,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '02483045022100ea84f21a2b3eeeb21d3fffd9611c56378806661b8ffdec3c087e5e95568534f8022008838b39b196daed9a4a4681cd658b42dbe36cbbb5834845dd1606c9c34cc95181210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 5,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 8340000,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 5}],
      'n': 0,
      'tx_index': 4187181310732894,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '0247304402206b90af883eaf278cac70d85daef76e0f67248b4cfb132be2f95bfd15a3bcf775022075d91970fea533945c9a1fc5818444b878eb6c3ea73585ce05ffbd9c9415480781210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 6,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 17859199,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 6}],
      'n': 0,
      'tx_index': 5932489054638892,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '0247304402207d75bd915e48da01da045cb0beb1941b383e86978fd5f616a60567788d5e140002204e67c148e85e6d64a98b76ec811f1852ee3784058bd4697e5f3bf3ce2a1911be81210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 7,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 17000000,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 7}],
      'n': 0,
      'tx_index': 5613628715645041,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '0247304402204f71f048b189fb5460813b1f83cf0257041161cc9ba4938b8abe43d9c37487ee022020d9d2ba938715b64a308cd3645c3c8d1d2ddd0a0187fa12e6697fc4feb122a881210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 8,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 122193180,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 8}],
      'n': 0,
      'tx_index': 8649068834061160,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '0247304402204ce4726bc975f2eac8c9fb29f60044078234c938325b43802a4b6e116c0021f802207741a679ed372f07a76648b7b73c99366a53df471c6419ac0fec698f3de9c24681210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 9,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 37007820,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 9}],
      'n': 0,
      'tx_index': 8813986154078941,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}},
    {'sequence': 4294967295,
     'witness': '02483045022100ef55addf9aacafa206888bcbc0714ad4baa93498d878f9766b5ea9fc6becfc0a022072776c7b2546f74e4b7af14fa74e854442dae8411e2e4eb4b82d7e923fad663681210287a1fb90f6065ba24c7e0b4b714a9c7f9be67e7173dac7e8c3f02dc5e468744a',
     'script': '',
     'index': 10,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 11927015,
      'spending_outpoints': [{'tx_index': 5762267476876206, 'n': 10}],
      'n': 0,
      'tx_index': 8931600616723740,
      'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
      'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 300000000,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 5762267476876206,
     'script': '00143dbb75961cfb59bb86656636bc8617a4679282a9',
     'addr': 'bc1q8kaht9suldvmhpn9vcmtepsh53ne9q4fdcjrhy'},
    {'type': 0,
     'spent': False,
     'value': 281345443,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 5762267476876206,
     'script': '00147a498404b05f69d56caecdea4acf07e2a9efc621',
     'addr': 'bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc'}]},
  {'hash': 'b1b3cb1d9b64a7b53817a72fabf11c7446d42d01cae86bdb797601425abfa436',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 2,
   'size': 222,
   'weight': 558,
   'fee': 477,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 1922598812794926,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967293,
     'witness': '02483045022100f0fb81ec227f9e6a30fbfaf2e320bd0f7da556488c3e1dc11299deed9bf0bd3a0220429735964c87abeb46e9d1244489a575178298ab651fed65dc27a9d85c7487150121037b72b3c3f3d7e4107fa7a08ecffd74dc16ee332abe6eafabd89acea8bdc66f42',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 6704,
      'spending_outpoints': [{'tx_index': 1922598812794926, 'n': 0}],
      'n': 0,
      'tx_index': 7166086684611379,
      'script': '00145598af355466d36e6a671374abbb2b75ef477956',
      'addr': 'bc1q2kv27d25vmfku6n8zd62hwetwhh5w72kxpw8cd'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 6227,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 1922598812794926,
     'script': '00145598af355466d36e6a671374abbb2b75ef477956',
     'addr': 'bc1q2kv27d25vmfku6n8zd62hwetwhh5w72kxpw8cd'},
    {'type': 0,
     'spent': False,
     'value': 0,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 1922598812794926,
     'script': '6a5d1214011400ff7f818cec82d08bc0a88281d215'}],
   'rbf': True},
  {'hash': '4c58fbe6a56f1acaef1b2ecc93432d7d1b17a686713506b4d67e326d0c6af732',
   'ver': 2,
   'vin_sz': 2,
   'vout_sz': 1,
   'size': 339,
   'weight': 1356,
   'fee': 1690,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 1793222960326223,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967293,
     'witness': '',
     'script': '483045022100e7f51babbb7ac2615d7fd661c3839256485c190acbdc04a887923d2b3a59a5fb022050fd8b33154f97f7d091505f6fd92d7641201ee9eaf03fab7e3fb75d4bdbecda012102ae0e147e2b0d1dc8a19255d8a5883a1025b5a29a5fba51a87ceeaab8d8a2a527',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 6353670,
      'spending_outpoints': [{'tx_index': 1793222960326223, 'n': 0}],
      'n': 12,
      'tx_index': 3076989068048228,
      'script': '76a91416c746fca3da01d2ebc26c8710f3748c9a6da23d88ac',
      'addr': '135SbFTc5rJNR7fmZJo5nQQZgQhEqQULkj'}},
    {'sequence': 4294967293,
     'witness': '',
     'script': '473044022039ece44bd9514fee67336be62e3f690f56d12e61485da49d2f96487491a9fde502201a863c37a5397935f1577dad6fe701d4e4b40ca78fb79dfae6be2f52a76d9e65012102ae0e147e2b0d1dc8a19255d8a5883a1025b5a29a5fba51a87ceeaab8d8a2a527',
     'index': 1,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 105188,
      'spending_outpoints': [{'tx_index': 1793222960326223, 'n': 1}],
      'n': 1,
      'tx_index': 2463517341000149,
      'script': '76a91416c746fca3da01d2ebc26c8710f3748c9a6da23d88ac',
      'addr': '135SbFTc5rJNR7fmZJo5nQQZgQhEqQULkj'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 6457168,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 1793222960326223,
     'script': '76a91472a813eab18b2fddb696643e96e4858b9a5d7c4088ac',
     'addr': '1BTFP7u79zxAHKL5xxwwTKrDvtxwVTDby5'}],
   'rbf': True},
  {'hash': '2ecd4753b453409742f2947d3e00b6f7b70b3c53a6eb6a947462af2b031d3b2f',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 2,
   'size': 222,
   'weight': 558,
   'fee': 473,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 1661789962335724,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967293,
     'witness': '024830450221008c88e6d01b7ae57761b07c23b6dd05fd00aaa1276a0147f6ff3e1928501ca65302206bae060effc71612a15c7c5868577e0e2c2b79cb30c2ad34e77a76cf37625fd9012103797e7766f059cbd61bc85009ebaa7e723f81cbd0681db08832860fc942c0778e',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 20077,
      'spending_outpoints': [{'tx_index': 1661789962335724, 'n': 0}],
      'n': 0,
      'tx_index': 4830161861891660,
      'script': '00145ad85d1c62b85b7e946b952da68835846491042d',
      'addr': 'bc1qttv968rzhpdha9rtj5k6dzp4s3jfzppdqjjuef'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 19604,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 1661789962335724,
     'script': '00145ad85d1c62b85b7e946b952da68835846491042d',
     'addr': 'bc1qttv968rzhpdha9rtj5k6dzp4s3jfzppdqjjuef'},
    {'type': 0,
     'spent': False,
     'value': 0,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 1661789962335724,
     'script': '6a5d1214011400ff7f818cec82d08bc0a88281d215'}],
   'rbf': True},
  {'hash': 'a21f56a04c665e9b5433a42368d16f88385e94ecbe189ebecc210ea2c706a60d',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 1,
   'size': 191,
   'weight': 437,
   'fee': 524,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 480215343317444,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967295,
     'witness': '0247304402204c0bdc8b9946f78fea9734a4c145df7120471b3ac94c934d2d5606f5bf5674e6022026d43603261624bb97ce71e4f17d566a104a487c7431e8314a6ec72970990bd3012103fe64183caac6d5b3c41395f038cd38e641194389b71ce4ccef288571442ee7e8',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 206113,
      'spending_outpoints': [{'tx_index': 480215343317444, 'n': 0}],
      'n': 0,
      'tx_index': 3429303280836132,
      'script': '0014bd71846017a9fec91ed25c15d8bf52bfa4e56133',
      'addr': 'bc1qh4ccgcqh48lvj8kjts2a306jh7jw2cfna0hpzh'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 205589,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 480215343317444,
     'script': '0014bf666aca9e0ba25e634ed307f4a43aae2cc3b658',
     'addr': 'bc1qhanx4j57pw39uc6w6vrlffp64ckv8djc30dd99'}]},
  {'hash': '0305c0356a207d1d5e20958d6721e8578fa95eb77853f5d4987d12ac1ddf920c',
   'ver': 1,
   'vin_sz': 1,
   'vout_sz': 1,
   'size': 191,
   'weight': 764,
   'fee': 955,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 442398336713295,
   'double_spend': False,
   'time': 1787848623,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967295,
     'witness': '',
     'script': '473044022017316858259c281c19ecfc572fed51094bf6ea623efa878c12265a468808a04102206150f3dfd45ff68ea377757f13e4d039aeda2f688fc799ea40e37c359097abb70121037b0ab2cace46d8937714a6b7162e36b2f77f38bcfe58c1e1ffdbe476734a2795',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 55122744,
      'spending_outpoints': [{'tx_index': 442398336713295, 'n': 0}],
      'n': 0,
      'tx_index': 3079851096827613,
      'script': '76a91415268e5d1f78c61914dcc281ba9f7628d37b2d0d88ac',
      'addr': '12vqNxKeNTanN8rgsnwSd9Wv5SwDaPU6TG'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 55121789,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 442398336713295,
     'script': '76a9145cfabde0e97b9f25aa998db0b6cc863af738849388ac',
     'addr': '19UdYVJovXqt6p26bMMXrAyx8PZeMLbMdr'}]},
  {'hash': '154a8a9d63d5f4a7ffecd026ed3da93c201285ee59b4344dfa517ec1639d1baf',
   'ver': 1,
   'vin_sz': 1,
   'vout_sz': 2,
   'size': 206,
   'weight': 617,
   'fee': 188,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 6161060465225674,
   'double_spend': False,
   'time': 1787848622,
   'block_index': None,
   'block_height': None,
   'inputs': [{'sequence': 4294967295,
     'witness': '0141bb8b5b3989a84184de2ac6f6c8fed90ba330e5f18d9fc6386d5a7d740fe9f05a02f2a974314fd9394789d587a9cee6cc9d0635acb478cf7670a08c726e4960ac01',
     'script': '',
     'index': 0,
     'prev_out': {'type': 0,
      'spent': True,
      'value': 1618658,
      'spending_outpoints': [{'tx_index': 6161060465225674, 'n': 0}],
      'n': 0,
      'tx_index': 232722206910079,
      'script': '5120a3d1328864fd7f90ed1df13210356089a828e0c8a7f996d4bef1b2fbc4281729',
      'addr': 'bc1p50gn9zryl4lepmga7yepqdtq3x5z3cxg5lued4977xe0h3pgzu5sffdq0x'}}],
   'out': [{'type': 0,
     'spent': False,
     'value': 662,
     'spending_outpoints': [],
     'n': 0,
     'tx_index': 6161060465225674,
     'script': '5120ae2f17d8de1d3599990fb723498170a9e53294cfc2b4a009cde0a1583c1fa42f',
     'addr': 'bc1p4ch30kx7r56enxg0ku35nqts48jn99x0c262qzwduzs4s0ql5shsqrm8ed'},
    {'type': 0,
     'spent': False,
     'value': 1617808,
     'spending_outpoints': [],
     'n': 1,
     'tx_index': 6161060465225674,
     'script': '002019e70a9615159ddc1c9c5eff718410aecdefecce52979808c086dd5cab12343a',
     'addr': 'bc1qr8ns49s4zkwac8yutmlhrpqs4mx7lmxw22teszxqsmw4e2cjxsaqqlh7jv'}]},
  {'hash': 'ab81a5a39f665a1b3b88cbc3714fd2faa6d8ee573d05ca91323eb14fe4e773bf',
   'ver': 2,
   'vin_sz': 1,
   'vout_sz': 1,
   'size': 191,
   'weight': 437,
   'fee': 39,
   'relayed_by': '0.0.0.0',
   'lock_time': 0,
   'tx_index': 6736145044600359,
   'double_spend': False,
   'time': 1787848621,
   'block_index': None,

Lee la documentación de la API:

- Revisa la sección de endpoints disponibles. En un markdown, apunta como mínimo a dos enpoints diferents.

- Comprueba si ofrecen filtros o parámetros opcionales interesantes. Anótalo en un markdown.

- Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio)

**El primer endpoint es**: "https://blockchain.info/latestblock"
que muestra el bloque más reciente validado y añadido de forma permanente a una cadena de bloques.
Los campos principales son 'hash', 'time', 'block_index', 'height' y 'txIndexes'

**El segundo endpoint es**: "https://blockchain.info/unconfirmed-transactions?format=json"
que muestra un diccionario que contiene una lista de transacciones ('txs'), donde cada transacción es a su vez un diccionario.
Los campos principales son 'hash' y una serie de datos relacionados con las transacciones ('size','weight','fee','time') y otros diccionarios dentro.

Se confirma que la respuesta es JSON, ya que ha sido posible usar el método .json() de la libreria requests sin errores, obteniendo un diccionario de Python para su lectura.

Haz una petición GET sencilla:

- Muestra el código de estado de la respuesta
- Imprime de forma clara algnos de los campos de respuesta JSON

In [48]:
#conocer el código del estado de la consulta. para hacerlo más fácil y ayudarme en el siguiente paso, los guardaré en variables
datos1 = response1.status_code
datos2 = response2.status_code
print(f"El estado de código de la petición 1 es: {datos1}")
print(f"El estado de código de la petición 2 es: {datos2}")

El estado de código de la petición 1 es: 200
El estado de código de la petición 2 es: 200

In [49]:
#imprimo algunos de los campos de respuesta JSON
datos1 = response1.json()
hash = datos1["hash"]
time = datos1["time"]

print(f"El hash es: {hash}")
print(f"El tiempo es: {time}")

El hash es: 0000000000000000000040898fe3efc9d6d6b27de1fbe3b231ecf7046293faca
El tiempo es: 1787848386

In [50]:
#imprimo algunos de los campos de respuesta JSON
datos2 = response2.json()
hash = datos2["txs"][0]["hash"]
fee = datos2["txs"][0]["fee"]
print(f"El hash es: {hash}")
print(f"El peso es: {fee}")

El hash es: bf9e410013a4ffc8a9e0bbe95f2be1d92ab1831df37b003d92fa6a053b8d80e4
El peso es: 278

Convierte los datos a un DataFrame de pandas:

- Muestra las primera filas del Dataframe

In [51]:
#para pasarlo a dataframe, envuelvo la variable entre corchetes precisamente por que es una lista con un único diccionario dentro. Solo muestra una fila por que solo almacena el último registro
df_datos1 = pd.DataFrame([datos1])
df_datos1

,hash,time,block_index,height,txIndexes
0,0000000000000000000040898fe3efc9d6d6b27de1fbe3...,1787848386,964323,964323,"[695966919965635, 6751179972774911, 4827173109..."

In [52]:
#en este caso, al tratarse de un diccionario que contiene una lista de transacciones bajo la clave txs. Para pasarloa dataframe accedo directamaente a datos2["txs"] que ya es una lista de diccionarios lista para usar
df_datos2 = pd.DataFrame(datos2["txs"])
df_datos2

,hash,ver,vin_sz,vout_sz,size,weight,fee,relayed_by,lock_time,tx_index,double_spend,time,block_index,block_height,inputs,out,rbf
0,bf9e410013a4ffc8a9e0bbe95f2be1d92ab1831df37b00...,1,1,2,222,561,278,0.0.0.0,0,8039704844873055,False,1787848623,None,None,"[{'sequence': 4294967293, 'witness': '02473044...","[{'type': 0, 'spent': False, 'value': 683, 'sp...",True
1,94268a34bb0c777b226952d7984549cd93fd1a32324b4f...,2,1,2,225,573,322,0.0.0.0,0,7568518019680362,False,1787848623,None,None,"[{'sequence': 4294967293, 'witness': '02473044...","[{'type': 0, 'spent': False, 'value': 477683, ...",True
2,b4652f5f66328ce6d4b24c18f020016d58bba93c1fb3f0...,1,11,2,1708,3277,3412,0.0.0.0,0,5762267476876206,False,1787848623,None,None,"[{'sequence': 4294967295, 'witness': '02483045...","[{'type': 0, 'spent': False, 'value': 30000000...",NaN
3,b1b3cb1d9b64a7b53817a72fabf11c7446d42d01cae86b...,2,1,2,222,558,477,0.0.0.0,0,1922598812794926,False,1787848623,None,None,"[{'sequence': 4294967293, 'witness': '02483045...","[{'type': 0, 'spent': False, 'value': 6227, 's...",True
4,4c58fbe6a56f1acaef1b2ecc93432d7d1b17a686713506...,2,2,1,339,1356,1690,0.0.0.0,0,1793222960326223,False,1787848623,None,None,"[{'sequence': 4294967293, 'witness': '', 'scri...","[{'type': 0, 'spent': False, 'value': 6457168,...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53febc49abb2b0bd0aa910ac4fac164d98076815db54bd...,1,3,2,563,1187,365,0.0.0.0,0,7857916614956073,False,1787848602,None,None,"[{'sequence': 4294967295, 'witness': '0141d729...","[{'type': 0, 'spent': False, 'value': 37355, '...",NaN
96,bcf6df9758cefed00e6727526f922c6794fc76bc3ba7be...,2,2,1,344,722,183,0.0.0.0,0,7176602837585693,False,1787848602,None,None,"[{'sequence': 4294967293, 'witness': '02483045...","[{'type': 0, 'spent': False, 'value': 58346, '...",True
97,277538cacfec0f75722b6943af713618566f8deed0bfda...,2,1,2,221,557,443,0.0.0.0,0,5868297410821625,False,1787848602,None,None,"[{'sequence': 4294967293, 'witness': '02473044...","[{'type': 0, 'spent': False, 'value': 9594, 's...",True
98,30e5d9a61ace60f00e9add4218aa1ce263da06fe138abc...,2,1,2,414,792,318,0.0.0.0,964321,5114369335584356,False,1787848602,None,None,"[{'sequence': 4294967293, 'witness': '04004730...","[{'type': 0, 'spent': False, 'value': 5975611,...",True
99,cad9859eb89fb081bb5d7a9c3b1f776abee555a302e206...,1,1,2,234,609,306,0.0.0.0,0,4565552368950845,False,1787848602,None,None,"[{'sequence': 4294967295, 'witness': '02473044...","[{'type': 0, 'spent': False, 'value': 2999668,...",NaN

In [53]:
#para desanidar un nivel más, cada transacción tiene una lista de  "inputs". Con meta indico que los campos hash fee y time pertenecen al primer nivel (txs), y marco la ruta completa ["txs","hash"] para mostrar esas columnas de primer nivel
df_datos2 = pd.json_normalize(
    datos2,
    record_path=["txs","inputs"],
    meta=[['txs','hash'],['txs','fee'],['txs','time']]
)
df_datos2

,sequence,witness,script,index,prev_out.type,prev_out.spent,prev_out.value,prev_out.spending_outpoints,prev_out.n,prev_out.tx_index,prev_out.script,prev_out.addr,txs.hash,txs.fee,txs.time
0,4294967293,0247304402200e5e6ed951771b35f1421b148b77dba2de...,,0,0,True,29619,"[{'tx_index': 8039704844873055, 'n': 0}]",0,6920284783195131,0014bfb0ceed3d20c419befd24fab974b5f181313ca5,bc1qh7cvamfayrzpn0haynatja947xqnz099el89hu,bf9e410013a4ffc8a9e0bbe95f2be1d92ab1831df37b00...,278,1787848623
1,4294967293,024730440220751faf9a667df1b4692075c32d274ca906...,,0,0,True,521663,"[{'tx_index': 7568518019680362, 'n': 0}]",0,1232654863526218,00147ef1896fdf6f11a781e583a7f380e2e43fd980f8,bc1q0mccjm7ldug60q09swnl8q8zuslanq8cxp2gaa,94268a34bb0c777b226952d7984549cd93fd1a32324b4f...,322,1787848623
2,4294967295,02483045022100e3e6386e17fb88faea94968ef9ce60b1...,,0,0,True,30000000,"[{'tx_index': 5762267476876206, 'n': 0}]",0,5574514746435713,00147a498404b05f69d56caecdea4acf07e2a9efc621,bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc,b4652f5f66328ce6d4b24c18f020016d58bba93c1fb3f0...,3412,1787848623
3,4294967295,0247304402200e41ca12072c7123c06aacf0043f2bb037...,,1,0,True,14806900,"[{'tx_index': 5762267476876206, 'n': 1}]",0,3971237944223387,00147a498404b05f69d56caecdea4acf07e2a9efc621,bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc,b4652f5f66328ce6d4b24c18f020016d58bba93c1fb3f0...,3412,1787848623
4,4294967295,02483045022100bd165becd9e576a3e9bd4608ef4d5d36...,,2,0,True,6108882,"[{'tx_index': 5762267476876206, 'n': 2}]",0,6686152831020606,00147a498404b05f69d56caecdea4acf07e2a9efc621,bc1q0fycgp9sta5a2m9weh4y4nc8u257l33p5tzykc,b4652f5f66328ce6d4b24c18f020016d58bba93c1fb3f0...,3412,1787848623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,4294967293,02483045022100b826d4fd2c3d57d37371618df84c3eb0...,,0,0,True,30774,"[{'tx_index': 7176602837585693, 'n': 0}]",2,7471125184489629,00141f091b53289ab5ae5db3e382c2b74a48d89f62e0,bc1qruy3k5egn266uhdnuwpv9d62frvf7chqplpnsh,bcf6df9758cefed00e6727526f922c6794fc76bc3ba7be...,183,1787848602
206,4294967293,02483045022100cd5d5d48f184c0ce07205f468e301f05...,,1,0,True,27755,"[{'tx_index': 7176602837585693, 'n': 1}]",18,8380104736770842,00141f091b53289ab5ae5db3e382c2b74a48d89f62e0,bc1qruy3k5egn266uhdnuwpv9d62frvf7chqplpnsh,bcf6df9758cefed00e6727526f922c6794fc76bc3ba7be...,183,1787848602
207,4294967293,02473044022008086cd7c732e0876b1beaef0d549cf0de...,,0,0,True,10037,"[{'tx_index': 5868297410821625, 'n': 0}]",0,5473940507070030,00145598af355466d36e6a671374abbb2b75ef477956,bc1q2kv27d25vmfku6n8zd62hwetwhh5w72kxpw8cd,277538cacfec0f75722b6943af713618566f8deed0bfda...,443,1787848602
208,4294967293,040047304402203a2766ac37cc1a4550c81bd19a7239d8...,,0,0,True,18396500,"[{'tx_index': 5114369335584356, 'n': 0}]",1,1314272008288201,00209ab4659824e92de01bddb37db69d09b4fa009024f7...,bc1qn26xtxpyayk7qx7akd7md8gfknaqpypy7u8826cqw8...,30e5d9a61ace60f00e9add4218aa1ce263da06fe138abc...,318,1787848602
209,4294967295,02473044022002ddc8d1bd4b787eb5ad28473ac62d8dd1...,,0,0,True,5600000,"[{'tx_index': 4565552368950845, 'n': 0}]",0,3610410283844225,001495e98c3b1ebeba00f0fb9d486fc227526e782927,bc1qjh5ccwc7h6aqpu8mn4yxls382fh8s2f8mvpgkx,cad9859eb89fb081bb5d7a9c3b1f776abee555a302e206...,306,1787848602

**Nivel 3**

Utiliza la API de Open BCN para:

- Encontrar un DataSet de tu interés mediante package_search y package_show

In [54]:
#el primer endpoint es con package_search y paso una string para que busque la palabra economia (uso la q con package_search)
url_base = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_search?q=economia"
respuesta = requests.get(url_base)
datos = respuesta.json()
datasets = datos["result"]["results"]
print(len(datasets))

10

En la siguiente celda, hago un bucle anidado for, con un condicional if para que muestre los ids de los datasets que tengan formato csv

In [55]:
for dataset in datasets:
    #print(dataset['title'])
    #print(dataset["id"])
    print(f"{dataset["title"]} - {dataset["id"]}")
    for recurso in dataset["resources"]:
      if recurso["format"] == "CSV":
        print(recurso["id"])

Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council - 331cba6c-7ca7-49d7-8ec7-19ff39d70aa3
806839e7-6798-48c9-bf04-caf045c959c1
fb3d9998-3d60-407c-8654-948b5603862c
Receipts and quota of the register of the Vados Tax of the Barcelona City Council - 7e63eeb0-670a-4bcc-bee9-1d89697a4501
e35dce7d-96f6-4130-b794-42967da2cce5
5f5e606d-4a38-4b4a-a16a-38e024e0b642
Receipts and charges from the motor vehicle tax roll of the Barcelona City Council - e21b436f-7f84-4f7b-a3de-f7dc6b43264f
110749d9-ee3e-4d1f-b962-680e3cebe608
Receipts and quota of the register of the Fee for private use of the public thoroughfare (nightstands and terraces) of the Barcelona City Council - f725406c-9c7a-4ed1-86cb-3358d6fb4dd0
7c8e7078-c52e-40f6-9123-af196387e057
da13ea98-1a06-4eca-9dd0-36848c3f2b54
b821a0e7-eb15-4c89-bae8-f8f21f1996b6
Vehicle types in traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council - bf7a733a-1faa-4ec8-ba1d-b4461df9f84a
0ad04b34-c306-4d88-bd7f-dbead3926ec3
d42a2586-b675-4691-af9e-e5b4b71066a7
93cc8547-55af-407c-b1ea-160574ab0c89
802f0653-5b01-413f-b8ce-9e2b676a58b7
Quota of the register of Economic Activities Tax of the Barcelona City Council  - ddc0cdee-229c-4bcd-aa71-ec959e6cee33
dad8b9a3-4f38-47d1-a200-4740b9f83283
2941af99-4bdb-42a7-8d4a-5c8cd79c1f16
94a555a9-ebb4-438e-9f82-ad557da6028f
106585ec-d7d7-4f7b-ba29-07b924b663b2
Fees from the Barcelona City Council property tax register - 4a9f4fc9-47e6-4c0c-a33b-34ada4c98d37
45fd82a0-c7c5-47d7-a59f-7d0d677b7d7d
04940da6-24a3-454c-b156-fe8e88a803d4
681c42e3-b2ae-478d-aa3d-906f1c40c398
ce060070-a463-4719-9a9e-a58086dcc3e4
Official coding of traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council - b388d80c-8a96-495a-99a0-a0c2c0b9de10
f91885d2-0307-444d-965b-56f3c9ef065c
ee726afa-bc23-4058-8256-364d2bd9bd2a
3f8d4a2c-01cd-4a36-9cae-19bfd9ef9027
864db65a-5280-40f2-8f6e-f783245a16db
Related concepts with traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council - 26eefc76-bd48-4dcd-8402-b43f4a86cd6f
f9387635-532f-444d-ad67-15e0a395096b
dc497b4b-1972-41e5-8e48-ed04a0175006
22b06dcb-7a7b-4b47-991b-8e7c9c9b338d
59e1ec05-703b-4b61-9409-6f305ae8cc7f
Detail of traffic complaints and sanctions processed by the Institut Municipal d’Hisenda of Barcelona City Council - ce80eb0b-0d99-4470-94f8-b09ce818b061
e483d5d2-132b-4d70-940c-03f63e73fe58
0b463a28-e6c8-40dd-9416-f076be04fd66
fa17916a-7004-4c57-a7da-5660c50dc846
5693bb33-9212-44df-9c67-a90a5fc06838
13d6e4ad-c6af-49be-adfb-677c7a3a0fc9
0e1a8397-6594-4cf1-b1d7-c4df5d2d2598
32ea930b-0576-4084-bf44-02c5e27d5405
f777fb65-3a12-4edc-9842-b18ba8a774a6
0821baa5-ea3b-49fa-ac10-143ab26d8657
884e3d45-1eb1-4ee7-958b-b5a03e9ece23
2b4b09b6-f459-4132-be27-f479e76a4d2c
ab19d98d-f10d-454b-be8c-1c8d1ea328e5
c51dee3c-8429-4746-93a0-f2bd45b9d67e
bb87c33b-1d30-4e61-8c78-fa83473ce6d6
08b93b6a-7679-4014-acc0-e04aeb698595
b06b5e05-fbb7-4ff1-aeb4-f8317d5b6b8a

De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON

In [56]:
#el segundo endpoint es con packache_show y le paso el id de un dataset con recursos disponibles en csv
url_show = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_show?id=331cba6c-7ca7-49d7-8ec7-19ff39d70aa3"
respuesta_show = requests.get(url_show)
print(json.dumps(respuesta_show.json(), indent=4, ensure_ascii=False))

{
    "help": "https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show",
    "success": true,
    "result": {
        "notes_translated": {
            "ca": "Quotes sense IVA del padró del preu públic de recollida de residus (sense grans productors ) de l’Ajuntament de Barcelona per districte, tipus de productor, secció, epígraf i classificació de la fracció residual generada. No inclou les liquidacions emeses posteriors a la publicació del padró.",
            "en": "Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council, by district, producer type, section, heading (tariff item) and classification. It does not include settlements made after the publication of the register.",
            "es": "Cuotas sin IVA del padrón del precio público de recogida de residuos (sin grandes productores) del Ayuntamiento de Barcelona por distrito, tipo de productor, sección, epígrafe y clasificación de la fracción residual generada. No incluye las liquidaciones posteriores a la publicación del padrón."
        },
        "geolocation": "No",
        "dades_alt_valor": "No",
        "url_tornada": {
            "ca": "https://ajuntament.barcelona.cat/neteja-i-residus/ca/recollida-domestica/la-taxa-de-recollida-de-residus-municipals",
            "en": "https://ajuntament.barcelona.cat/neteja-i-residus/es/recogida-domestica/la-tasa-de-recogida-de-residuos-municipales",
            "es": "https://ajuntament.barcelona.cat/neteja-i-residus/es/recogida-domestica/la-tasa-de-recogida-de-residuos-municipales"
        },
        "dataset_fields_description": "",
        "fuente": "Ajuntament de Barcelona",
        "tag": "Any 2024,Any 2025,Impost,Quotes,Residus,Preu públic",
        "private": false,
        "num_tags": 6,
        "code": "rebuts-quota-padro-residus-bcn",
        "frequency": "ANUAL",
        "id": "331cba6c-7ca7-49d7-8ec7-19ff39d70aa3",
        "title_translated": {
            "ca": "Quotes sense IVA del padró del preu públic de recollida de residus (sense grans productors ) de l’Ajuntament de Barcelona",
            "en": "Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council",
            "es": "Cuotas sin IVA del padrón del precio público de recogida de residuos (sin grandes productores) del Ayuntamiento de Barcelona"
        },
        "metadata_modified": "2026-02-09T08:22:08.509094",
        "author": "Gerència d'Àrea d'Economia, Recursos i Transformació Digital",
        "author_email": null,
        "isopen": true,
        "long_format": "No",
        "state": "active",
        "version": "",
        "mar_od": "No",
        "relationships_as_object": [],
        "department": "Departament de Bases de Dades i Secretaria Tècnica",
        "creator_user_id": "9a1528df-3413-4449-a875-638d55f91982",
        "type": "dataset",
        "resources": [
            {
                "api_access_number_absolute": 27,
                "cache_last_updated": null,
                "incorporated_in_cityos_res": "No",
                "token_type": "",
                "package_id": "331cba6c-7ca7-49d7-8ec7-19ff39d70aa3",
                "datastore_active": true,
                "id": "806839e7-6798-48c9-bf04-caf045c959c1",
                "description": "",
                "state": "active",
                "api_access_number": 17,
                "size": "1181123",
                "token_required": "",
                "hash": "",
                "token_name": "",
                "format": "CSV",
                "downloads": 98,
                "mimetype_inner": null,
                "url_type": "upload",
                "token_provider": "",
                "column_types": "",
                "hide_url": "",
                "token_version": "",
                "mimetype": null,
                "cache_url": null,
                "name": "2025_rebuts_quota_padro_residus_bcn.csv",
                "created": "2026-01-13T10:28:16.791530",
                "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/331cba6c-7ca7-49d7-8ec7-19ff39d70aa3/resource/806839e7-6798-48c9-bf04-caf045c959c1/download/2025_rebuts_quota_padro_residus_bcn.csv",
                "downloads_absolute": 130,
                "map_visualization_res": "none",
                "qa": {
                    "updated": "2026-08-27T02:10:21.794369",
                    "openness_score": 3,
                    "archival_timestamp": null,
                    "format": "CSV",
                    "created": "2026-01-14T02:12:45.718904",
                    "resource_timestamp": null,
                    "openness_score_reason": "This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3."
                },
                "last_modified": "2026-01-13T10:28:16.732158",
                "position": 0,
                "revision_id": "8515bff9-e6d4-4674-86f6-99e52b53716c",
                "resource_type": null
            },
            {
                "api_access_number_absolute": 7,
                "cache_last_updated": null,
                "incorporated_in_cityos_res": "No",
                "token_type": "",
                "package_id": "331cba6c-7ca7-49d7-8ec7-19ff39d70aa3",
                "datastore_active": true,
                "id": "fb3d9998-3d60-407c-8654-948b5603862c",
                "description": "",
                "state": "active",
                "api_access_number": 5,
                "size": "1104568",
                "token_required": "No",
                "hash": "",
                "token_name": "",
                "format": "CSV",
                "downloads": 35,
                "mimetype_inner": null,
                "url_type": "upload",
                "token_provider": "",
                "column_types": "",
                "hide_url": "No",
                "token_version": "",
                "mimetype": null,
                "cache_url": null,
                "name": "2024_rebuts_quota_padro_residus_bcn.csv",
                "created": "2026-01-13T10:26:34.239724",
                "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/331cba6c-7ca7-49d7-8ec7-19ff39d70aa3/resource/fb3d9998-3d60-407c-8654-948b5603862c/download/2024_rebuts_quota_padro_residus_bcn.csv",
                "downloads_absolute": 40,
                "map_visualization_res": "none",
                "qa": {
                    "updated": "2026-08-27T02:10:21.806143",
                    "openness_score": 3,
                    "archival_timestamp": null,
                    "format": "CSV",
                    "created": "2026-01-14T02:12:45.745549",
                    "resource_timestamp": null,
                    "openness_score_reason": "This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3."
                },
                "last_modified": "2026-01-13T14:41:13.441104",
                "position": 1,
                "revision_id": "8515bff9-e6d4-4674-86f6-99e52b53716c",
                "resource_type": null
            }
        ],
        "token_required": "No",
        "decalatgeNum": "N/A",
        "tags": [
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Any 2024",
                "id": "283fc2f8-cbae-4ef0-9884-edf991193b9f",
                "name": "Any 2024"
            },
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Any 2025",
                "id": "0510e622-4b6e-4f59-994f-41c01b0a8b1f",
                "name": "Any 2025"
            },
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Impost",
                "id": "28e97e18-f972-4275-bc7d-3100c8860a7f",
                "name": "Impost"
            },
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Preu públic",
                "id": "cfbffe57-21a6-4321-a35a-94af095301ce",
                "name": "Preu públic"
            },
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Quotes",
                "id": "e3990f2c-0991-40d5-a40e-d634c25ced2a",
                "name": "Quotes"
            },
            {
                "vocabulary_id": null,
                "state": "active",
                "display_name": "Residus",
                "id": "c0d03e30-0048-40eb-a3ae-fb7bc7e300e4",
                "name": "Residus"
            }
        ],
        "ODS_Principal_agenda_2030": "ODS 16: Pau, justícia i institucions sòlides",
        "fecha_publicacion": "2026-02-09",
        "ODS_Colateral2_agenda_2030": "N/A",
        "ODS_Colateral1_agenda_2030": "N/A",
        "license_id": "CC-BY-4.0",
        "hide_url": "No",
        "relationships_as_subject": [],
        "license_title": "Creative Commons Attribution 4.0",
        "groups": [],
        "num_resources": 2,
        "organization": {
            "description": "",
            "created": "2017-01-24T16:55:06.806043",
            "title": "Sector públic",
            "name": "sector-public",
            "is_organization": true,
            "state": "active",
            "image_url": "bcn-icon-punts-registre",
            "revision_id": "42a96f79-3356-4692-ad4a-923d811b8a9f",
            "type": "organization",
            "id": "5a597816-bbe2-4174-bf69-53644330bb5f",
            "approval_status": "approved"
        },
        "name": "rebuts-quota-padro-residus-bcn",
        "url": null,
        "notes": "Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council, by district, producer type, section, heading (tariff item) and classification. It does not include settlements made after the publication of the register.",
        "owner_org": "5a597816-bbe2-4174-bf69-53644330bb5f",
        "load_type": "ds_manual",
        "qa": {
            "openness_score_reason": "This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.",
            "updated": "2026-08-27T02:10:21.806143",
            "openness_score": 3
        },
        "api": "Yes",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "historical": "Yes",
        "title": "Fees excluding VAT from the public price register for waste collection (excluding large producers) of the Barcelona City Council",
        "revision_id": "40ecd8e3-a2c4-4edb-8a43-046710d76cbb",
        "extras": [
            {
                "key": "01.Codi_Districte",
                "value": "Codi de districte de l'activitat"
            },
            {
                "key": "02.Nom_Districte",
                "value": "Nom del districte de l'activitat"
            },
            {
                "key": "03.Tipus_Productor",
                "value": "Tipus de productor"
            },
            {
                "key": "04.Codi_Seccio",
                "value": "Codi de la secció"
            },
            {
                "key": "05.Descripcio_Seccio",
                "value": "Descripció de la secció"
            },
            {
                "key": "06.Codi_Epigraf",
                "value": "Codi de l'epígraf de l'activitat"
            },
            {
                "key": "07.Descripcio_Epigraf",
                "value": "Descripció de l'epígraf de  l'activitat"
            },
            {
                "key": "08.Codi_Fraccio_Residual _Generada",
                "value": "Codi de la fracció de residus"
            },
            {
                "key": "09.Descripcio_Fraccio_Residual_Generada",
                "value": "Descripció de la fracció dels residus"
            },
            {
                "key": "10.Total_Quota_Sense_IVA",
                "value": "Import sense IVA de la quota en €"
            }
        ]
    }
}

Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para:

- Recuperar, al menos, 100 registros

In [57]:
#utilizo el endpoint datastore_search, con uno de los ids obtenido anteriormente que tengan recursos en csv o json
url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=806839e7-6798-48c9-bf04-caf045c959c1"
respuesta_datastore = requests.get(url_datastore)
datos_ds = respuesta_datastore.json()
print(len(datos_ds['result']['records']))

100

Convertir los resultados en DataFrame

In [58]:
#conversion a dataframe
df = pd.json_normalize(datos_ds, record_path=['result','records'])#uso json_normalize para aplanar un json anidado, el record_path es para indicarle la ruta donde debe buscar, en result y dentro, record
df.head()

,Descripcio_Fraccio_Residual_Generada,Descripcio_Epigraf,Codi_Districte,Nom_Districte,Tipus_Productor,Codi_Epigraf,Descripcio_Seccio,Total_Quota_Sense_IVA,Codi_Seccio,Codi_Fraccio_Residual _Generada,_id
0,Resta,Arquitectes,6,Gràcia,MÍNIM,411,Activitats Professionals,1617,2,A,1
1,"Resta, paper-cartró, vidre i envasos",Altres serveis de cafeteries i bars,2,Eixample,MITJÀ,6732,Activitats Empresarials,299449.55,1,C,2
2,"Resta, paper-cartró, vidre i envasos",Altres serveis de cafeteries i bars,7,Horta-Guinardó,MITJÀ,6732,Activitats Empresarials,62042.09,1,C,3
3,Resta i paper-cartró,Comerç al detall de béns de segona mà,2,Eixample,MITJÀ,656,Activitats Empresarials,6040.99,1,B,4
4,"Resta, orgànica, paper-cartró, vidre i envasos",Serveis de restaurants d'una forquilla,1,Ciutat Vella,MITJÀ,6715,Activitats Empresarials,158332.64,1,E,5

Guardar el DataFrame en un archivo csv

In [59]:
df.to_csv("mis_resultados.csv", index=False)#to_csv para convertirlo. lo guarda en el entorno local de colab, no en el ordenador. Le quito el index para que no lo ponga como columna